import Footer from "@/components/Footer";
import Header from "@/components/Header";
import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import './globals.css';
const inter = Nunito_Sans({ subsets: ["latin"], weight: '400' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="max-w-[1440px] m-auto">{children}      </div>
        <Footer />
      </body>
    </html>
  );
}
